# Generated by Django 5.1.6 on 2025-03-17 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BRSExcel',
            fields=[
                ('id_brsexcel', models.AutoField(primary_key=True, serialize=False)),
                ('judul_brs', models.CharField(max_length=250)),
                ('id_file', models.CharField(max_length=100)),
                ('url_file', models.CharField(max_length=500)),
                ('tgl_terbit', models.DateField()),
                ('tgl_up', models.DateTimeField(auto_now=True)),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BRSsheet',
            fields=[
                ('id_brssheet', models.AutoField(primary_key=True, serialize=False)),
                ('judul_sheet', models.CharField(max_length=250)),
                ('file_sheet', models.CharField(max_length=500)),
                ('id_brsexcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myuser.brsexcel')),
            ],
        ),
    ]
